### ISSUE TITLE
Not working with an app service plan

### ISSUE THREAD

**Issue by BredStik** [anthonychu/functions-headless-chromium#1]
Awesome stuff by the way!  Managed to run it flawlessly in a consumption plan but this fails when using an app service plan.  Any reason why?

Thanks

**Comment by anthonychu** [comment]
If you have app insights enabled, can you see if there are any errors? If not, send me your app name, region, and approx time of error at antchu@microsoft.com and I can try to see if there is anything interesting in the logs on our side.

**Comment by BredStik** [comment]
Sorry, I should have given you more information.  It's as if the remote build is not executing.  The puppeteer module doesn't seem to be installed.  I get the following error:

Exception: Worker was unable to load function HttpTrigger: 'Error: Cannot find module 'puppeteer'

If I deploy the exact same code to a consumption plan function app, it works flawlessly.

**Edit:  just re-deployed, puppeteer module seemed to install, but got different error:

Stack: Error: Failed to launch the browser process!
[0821/171835.357718:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.**

**Comment by horihiro** [comment]
Hi @BredStik 
I also saw the exception you mentioned.

This should be resolved by setting an argument `--no-sandbox` to `puppeteer.launch` as following.

```js
        const browser = await puppeteer.launch({
            args: ['--no-sandbox']
        });
```

**Comment by BredStik** [comment]
@horihiro That did it!  Thank you so much!
