### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by nagaozen** [anthonychu/functions-headless-chromium#2]
Hi @anthonychu, this project is AWESOME! It's really close to the service I'm trying to deploy. Unfortunately I can't manage to make it work in a Linux Consumption Plan hosted in South Brazil. The appname is `looplex365-fns-lin` and the time of execution is around 5h15 AM, 7 sep 2020.

Already changed the code with @horihiro `--no-sandbox` fix with no effect.

![image](https://user-images.githubusercontent.com/22817/92366885-197f7700-f0cc-11ea-824d-3df898f5f953.png)

![image](https://user-images.githubusercontent.com/22817/92367107-5f3c3f80-f0cc-11ea-9c2f-739e20f6ea68.png)

Thanks,
nagaozen

**Comment by horihiro** [comment]
It seems there is no problem in your function code.
So I want you to check deployment option.

Could you please try followings when you deploy your functions?

  1. If you use VScode for deployment,
add `"azureFunctions.scmDoBuildDuringDeployment": true` into `.vscode/settings.json`
  2. if you use `func` command,
add `--build remote` option 

Please read `Deploy to Azure` section in following @anthonychu 's blog for details
https://dev.to/azure/running-headless-chromium-in-azure-functions-with-puppeteer-and-playwright-2fgk

Regards,

**Comment by nagaozen** [comment]
> It seems there is no problem in your function code.
> So I want you to check deployment option.
> 
> Could you please try followings when you deploy your functions?
> 
> 1. If you use VScode for deployment,
>    add `"azureFunctions.scmDoBuildDuringDeployment": true` into `.vscode/settings.json`
> 2. if you use `func` command,
>    add `--build remote` option
> 
> Please read `Deploy to Azure` section in following @anthonychu 's blog for details
> https://dev.to/azure/running-headless-chromium-in-azure-functions-with-puppeteer-and-playwright-2fgk
> 
> Regards,

Hi @horihiro, thank you for the feedback.

I'm using exactly the same files from the Anthony Chu article [Running headless Chromium in Azure Functions with Puppeteer and Playwright](https://anthonychu.ca/post/azure-functions-headless-chromium-puppeteer-playwright/). My `.vscode/settings.json` contents are:

```
{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.projectLanguage": "JavaScript",
    "azureFunctions.projectRuntime": "~3",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.scmDoBuildDuringDeployment": true
}
```

My `.funcignore` is:

```
*.js.map
*.ts
.git*
.vscode
local.settings.json
test
tsconfig.json
node_modules
```

I'm going to deploy to a US location to see if the problem persists.

Thanks,
nagaozen

**Comment by horihiro** [comment]
how about `func` command with `--build remote` ?

**Comment by nagaozen** [comment]
> how about `func` command with `--build remote` ?

Yeap, that made it work:

![image](https://user-images.githubusercontent.com/22817/92375141-13db5e80-f0d7-11ea-9422-91be3f30f058.png)

![image](https://user-images.githubusercontent.com/22817/92375378-6583e900-f0d7-11ea-8410-507e9b448e08.png)

Thank you @horihiro.

**Comment by nagaozen** [comment]
Strangely the `HTTP/1.1 500 Internal Server Error` is happening again.

Today I sent an update and the flow went better than the previous one. No `Unable to retrieve build status ...`

![image](https://user-images.githubusercontent.com/22817/95103946-a9383580-070b-11eb-89f7-d8578b28043d.png)
![image](https://user-images.githubusercontent.com/22817/95104000-b8b77e80-070b-11eb-8e2d-46b6f28fda50.png)
![image](https://user-images.githubusercontent.com/22817/95104049-c2d97d00-070b-11eb-8b56-b8ce396a9aca.png)

But when consuming the service, the `HTTP/1.1 500 Internal Server Error` is happening again:

![image](https://user-images.githubusercontent.com/22817/95104148-e43a6900-070b-11eb-95de-97fc7f50e599.png)

Anything different to the functionapp stack since we closed this issue?

**Comment by nagaozen** [comment]
Nevermind.
