### ISSUE TITLE
Cannot deploy to an existing function app

### ISSUE THREAD

**Issue by chris-trotter** [anthonychu/functions-headless-chromium#4]
When implementing this repo using puppeteer to an existing function app I had the following error in VS Code:
`Error: Run-From-Zip is set to a remote URL using WEBSITE_RUN_FROM_PACKAGE or WEBSITE_USE_ZIP app setting. Deployment is not supported in this configuration.`

**Solution**
Deploy the function to a new fresh function app. It appears existing function apps have a hidden flag called WEBSITE_RUN_FROM_PACKAGE or WEBSITE_USE_ZIP as I could not find these in environment variables in the Azure portal or within VS Code. I would imagine this is due to adding `"azureFunctions.scmDoBuildDuringDeployment": true` to the .vscode/settings.json file.

**Comment by anthonychu** [comment]
Did you manage to solve this? I think it's a bug in the way VS Code does its deployments. You can use `func azure functionapp publish $appname -b remote` to deploy and that'll get the app into the right state for deploying from VS Code again with `"azureFunctions.scmDoBuildDuringDeployment": true`.

**Comment by chris-trotter** [comment]
Anthony unfortunately I wasn't able to resolve. It was easier for me to simply create an entirely new function app. I also had difficulty in changing the trigger from http to a queue. Looks like once a binding is configured for http, changing to a queue using the function.json config won't cause the queue to be setup. However your template was invaluable and I managed to get puppeteer on a linux consumption azure function working in response to a queue trigger.
